name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout scripts repository
        uses: actions/checkout@v2
        with:
          repository: Danilmann/scripts
          path: scripts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Проверка пути к скрипту
        run: |
          echo "Текущий путь:"
          pwd
          echo "Содержимое директории:"
          ls -l
          echo "Содержимое директории scripts:"
          ls -l scripts

      - name: Parse file for variables
        run: |
          chmod +x scripts/parse-file.sh
          ./scripts/parse-file.sh ./pars-file
          # Экспорт переменных в среду GitHub
          source ./GITHUB_ENV
          echo "REPO_NAME=${repository_name}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${environment}" >> $GITHUB_ENV
          echo "APPLICATION=${application}" >> $GITHUB_ENV
          echo "TAG=${tag}" >> $GITHUB_ENV
          echo "Проверка экспорта переменных:"
          echo "REPO_NAME=${repository_name}"
          echo "ENVIRONMENT=${environment}"
          echo "APPLICATION=${application}"
          echo "TAG=${tag}"

      - name: Log all environment variables
        run: printenv | sort

      - name: Login to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Verify Docker login
        run: docker info

      - name: Build Docker image
        run: |
          echo "Building Docker image for application: ${{ env.APPLICATION }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/${{ env.APPLICATION }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/${{ env.APPLICATION }}:${{ env.TAG }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/${{ env.APPLICATION }}:${{ env.TAG }}

      - name: Test Docker container
        run: |
          docker run --rm --name test-container ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/${{ env.APPLICATION }}:${{ env.TAG }} \
          && echo "Docker image is working as expected."

      - name: Deploy Docker container
        run: |
          docker run -d --name ${{ env.APPLICATION }} -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}/${{ env.APPLICATION }}:${{ env.TAG }}

      - name: Проверка доступности контейнера
        run: |
          echo "Проверка доступности приложения на порту 3000"
          sleep 10  
          curl --fail http://localhost:3000 || (echo "Приложение не доступно на порту 3000" && exit 1)
