name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout scripts repository
        uses: actions/checkout@v2
        with:
          repository: Danilmann/scripts
          path: scripts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Проверка пути к скрипту
        run: |
          echo "Текущий путь:"
          pwd
          echo "Содержимое директории:"
          ls -l
          echo "Содержимое директории scripts:"
          ls -l scripts

      - name: Parse file for variables
        run: |
          chmod +x scripts/parse-file.sh
          ./scripts/parse-file.sh ./pars-file
          echo "REPO_NAME=${repository_name}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${environment}" >> $GITHUB_ENV
          echo "Проверка экспорта переменных:"
          echo "REPO_NAME=${repository_name}"
          echo "REPO_NAME=${repository_name}"
          echo "ENVIRONMENT=${environment}"

      - name: Log all environment variables
        run: printenv | sort

      - name: Build Docker image
        run: |
          echo "Building Docker image for repository: ${{ env.REPO_NAME }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }} .

      - name: Login to Docker Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Deploy Docker container
        run: |
          docker run -d --name ${{ env.REPO_NAME }} -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
